version: "3.8"

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "3.0.0"
        BUNDLER_VERSION: "2.2"
    image: seanfloydca:1.0.0
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
    environment:
      - APP_ENV=${APP_ENV:-development}
      - ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN}

  runner:
    <<: *app
    command: /bin/bash
    ports:
      - "3000:9292"
      - "3002:3002"

  sinatra:
    <<: *app
    command: bundle exec rackup config.ru -o 0.0.0.0
    ports:
      - "3000:9292"

volumes:
  bundle:
