version: 2.1
orbs:
  ruby: circleci/ruby@1.0.0
executors:
  ruby:
    docker:
      - image: "circleci/ruby:3.0.0"
jobs:
  build:
    executor: ruby
    working_directory: ~/seanfloyd.dev
    steps:
      - checkout
  test:
    executor: ruby
    environment:
      APP_ENV: test
      RACK_ENV: test
    steps:
      - checkout
      - ruby/install-deps:
          with-cache: false
      - run:
          name: Lint with Rubocop
          command: |
            bundle exec rubocop
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Code Climate before build
          command: |
            ./cc-test-reporter before-build
      - ruby/rspec-test
      - run:
          name: Code Climate Test Coverage
          command: |
            ./cc-test-reporter after-build -t simplecov
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b1:e6:4b:ef:3e:02:ae:c0:7a:06:b7:5c:5d:e6:23:6a"
      - run:
          name: Deploy to Dokku
          command: |
            ssh-keyscan -H seanfloyd.dev >> ~/.ssh/known_hosts
            git remote add dokku dokku@seanfloyd.dev:seanfloyd.dev
            git push -f dokku master
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
